{
    'name': 'FleetFlow',
    'version': '17.0.1.0.0',
    'summary': 'Fleet operations, trips, drivers, and maintenance management',
    'description': 'Production-ready fleet workflow management for Odoo 17.',
    'category': 'Operations/Fleet',
    'author': 'FleetFlow',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'data': [
        'security/fleetflow_security.xml',
        'security/ir.model.access.csv',
        'data/fleetflow_sequence.xml',
        'data/fleet_dashboard_data.xml',
        'data/fleet_trip_export_action.xml',
        'reports/fleet_vehicle_monthly_cost_report.xml',
        'views/fleet_actions.xml',
        'views/fleet_dashboard_views.xml',
        'views/fleet_command_center_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/fleet_driver_views.xml',
        'views/fleet_trip_views.xml',
        'views/fleet_maintenance_views.xml',
        'views/fleet_expense_views.xml',
        'views/fleetflow_menu.xml',
    ],
    'application': True, 
    'installable': True,
}
